# Generated by Django 5.2.13 on 2026-04-09 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('anio', models.PositiveIntegerField()),
                ('valor_auto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_poliza', models.CharField(max_length=50)),
                ('fecha_alta_poliza', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='siniestros.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siniestro', models.CharField(max_length=50, unique=True)),
                ('fecha_siniestro', models.DateField()),
                ('descripcion', models.TextField()),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sospechoso', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='siniestros.unidad')),
            ],
        ),
    ]
