# Generated by Django 6.0.4 on 2026-04-12 19:00

from django.db import migrations


def agregar_marcas(apps, schema_editor):
	Marca = apps.get_model('siniestros', 'Marca')
	marcas = [
		'Toyota',
		'Chevrolet',
		'Ford',
		'Volkswagen',
		'Fiat',
		'Renault',
		'Nissan',
		'Hyundai',
		'Peugeot',
		'Citroën',
		'BMW',
		'Mercedes-Benz',
		'Audi',
		'SEAT',
		'Kia',
		'Honda',
		'Suzuki',
		'Mitsubishi',
		'Jeep',
		'Subaru',
	]
	for marca_nombre in marcas:
		Marca.objects.get_or_create(nombre=marca_nombre)


def eliminar_marcas(apps, schema_editor):
	# Función inversa para hacer reversible la migración
	pass


class Migration(migrations.Migration):

	dependencies = [
		('siniestros', '0002_marca_unidad_marca'),
	]

	operations = [
		migrations.RunPython(agregar_marcas, eliminar_marcas),
	]
